# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f63a2fa52e3282bed1f16d588fd64d70b18cb659e7b571b95cba2a0e89ebff43720b3b2d9abf876852cbba96e98d22232f7120c6273393814204d0f981a7d37

test:
  secret_key_base: ae35d4ac9795f3d164d7896ed02388383c406a1ba34032127a78bc62f94af1a484bcb641dd7c7d860c94885f0b4c664b0d9ebcaec366056a890e165e5f4e9c05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
